#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM centos:7.4.1708

# Build CentOS 7 image with systemd enabled
# See https://hub.docker.com/_/centos/

# ENV container docker is mentioned in link above, but no explanation given.
# It does not by itself prevent excess systemd CPU usage due to:
# systemd[1]: Looping too fast. Throttling execution a little.
# observed when running journalctl
ENV container docker

RUN \
    # When installing from yum repo it is common to see:
    # Error : Public key for *.rpm is not installed
    # This can be resolved by importing the public key files for RPM
    # which may be found by running the following command
    # docker run --rm centos:7.4.1708 find / -name *GPG*
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Testing-7 && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Debug-7 && \
    # Install required packages
#    yum -y --setopt=tsflags=nodocs update && \
    # Install GNOME Desktop. The || true at the end of the line is a
    # dirty hack because gnome-keyring and mtr give an error:
    # Error unpacking rpm package... and the build fails. The following
    # resolves the dependencies but doesn't actually install those packages.
#    yum -y --setopt=tsflags=nodocs groups install "GNOME Desktop" && \
    # This seems to stop systemd going a bit berserk though there is no
    # explanation in the Dockerhub documentation as to *why* these cause
    # problems with systemd - needs some further investigation.
    # This tidy up of services needs to come after package installation.
    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;


# Seems to blacklist abrt OK but still systemd problems on shutdown
#yum -y --exclude=abrt* --setopt=tsflags=nodocs groups install "Base" && \


#ENTRYPOINT ["/sbin/init"]

#-------------------------------------------------------------------------------
# Example usage
# 
# Build the image
# docker build -t centos-gnome:7.4 .

