#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#FROM ubuntu-gnome-vgl:18.04
FROM linuxmint-cinnamon-vgl:19.3

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    xserver-xspice-hwe-18.04 spice-vdagent && \
#
#    echo '#!/bin/bash\nexec Xspice :2 -ac -noreset --auto --numheads 1 --disable-ticketing --vdagent -query localhost --video-codecs ${SPICE_VIDEO_CODECS:-gstreamer:h264;gstreamer:vp8;gstreamer:mjpeg;spice:mjpeg} --deferred-fps 60 > /dev/null' > /usr/bin/Xspice-lightdm-wrapper && \
#
#
#    echo '#!/bin/bash\nXspice $1 -ac -noreset --auto --numheads 1 --disable-ticketing --vdagent --video-codecs ${SPICE_VIDEO_CODECS:-gstreamer:h264;gstreamer:vp8;gstreamer:mjpeg;spice:mjpeg} --deferred-fps 60 > /dev/null&\nsleep 0.25\nkill -USR1 $PPID\ntail -F /var/log/lightdm/lightdm.log' > /usr/bin/Xspice-lightdm-wrapper && \
#
#    chmod +x /usr/bin/Xspice-lightdm-wrapper && \
#
#
    echo '[LightDM]\nminimum-display-number=1\n[Seat:*]\nuser-session=ubuntu-xorg\nxserver-command=/usr/bin/Xephyr-lightdm-wrapper\n[XDMCPServer]\nenabled=true' > /etc/lightdm/lightdm.conf.d/70-ubuntu.conf
#
#
#
#    echo '[LightDM]\nminimum-display-number=1\n[Seat:*]\nuser-session=ubuntu-xorg\nxserver-command=/usr/bin/Xspice-lightdm-wrapper' > /etc/lightdm/lightdm.conf.d/70-ubuntu.conf

#-------------------------------------------------------------------------------
# Example usage
# 
# Build the image
# docker build -t ubuntu-gnome-spice:18.04 .

# Using XDMCP sort of works - so far it needs Xspice to be started manually
# using the -query localhost option and XDMCPServer enabled in lightdm config
# The main issue is that I'm not clear it's possible to use XDMCP via a Unix
# domain socket and the DISPLAY gets set to <Docker IP>:2 not :2 and so
# Cinnamon goes into fallback mode 'cause VGL doesn't see the the host X server.

